#docker-compose.yml for NGINX Web Server

nginx:
  image: 'nginx:1.10'
  container_name: nginx
  restart: always
  ports:
    - '8000:80'
    - '9000:9000'
    - '9001:9001'
  volumes:
    - './nginx/webpages/:/usr/share/nginx/html'
    - './nginx/config/conf.d/:/etc/nginx/conf.d/'
    - './nginx/config/ssl:/etc/nginx/ssl'
    - './nginx/logs:/var/log/nginx'