#docker-compose.yml for redis server

redis:
  image: 'redis:3.2.3'
  container_name: redis
  restart: always
  ports:
    - '6379:6379'
  volumes:
    - './data/:/data/'
    #- './redis.conf:/usr/local/etc/redis/redis.conf'
